default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

DeepMindHumanoidBrain:
    normalize: true
    num_epoch: 3
    beta: 0.01
    time_horizon: 1000
    batch_size: 2048
    buffer_size: 20480
    gamma: 0.995
    max_steps: 2e6
    # max_steps: 625000
    summary_freq: 1000
    num_layers: 2
    hidden_units: 512
    # use_curiosity: true
    # curiosity_strength: 0.01
    # curiosity_enc_size: 256    

DeepMindHopperBrain:
    num_epoch: 10 
    time_horizon: 500 
    # summary_freq: 100000
    use_recurrent: false
    normalize: false 
    num_layers: 2
    hidden_units: 64 
    learning_rate: 3.0e-4
    batch_size: 64
    buffer_size: 2048 
    beta: .07
    # learning_rate: 1.0e-3
    # batch_size: 2048 
    # buffer_size: 10240 
    # beta: .003
    max_steps: 1.e6
    # max_steps: 62500


# DeepMindHopperBrain:
#     beta: 1.0e-2
#     epsilon: 0.20
#     gamma: 0.99
#     lambd: 0.95
#     learning_rate: 1.0e-3
#     num_epoch: 3
#     time_horizon: 128
#     summary_freq: 1000
#     use_recurrent: false
#     normalize: true
#     num_layers: 2
#     hidden_units: 90
#     batch_size: 2048
#     buffer_size: 10240
#     max_steps: 3e5
#     use_curiosity: true
#     curiosity_strength: 0.01
#     curiosity_enc_size: 256    

DeepMindWalkerBrain:
    beta: 1.0e-2
    epsilon: 0.20
    gamma: 0.99
    lambd: 0.95
    learning_rate: 1.0e-3
    num_epoch: 3
    time_horizon: 128
    summary_freq: 1000
    use_recurrent: false
    normalize: true
    num_layers: 3
    hidden_units: 41
    batch_size: 2048
    buffer_size: 10240
    max_steps: 3e5
    use_curiosity: true
    curiosity_strength: 0.01
    curiosity_enc_size: 256    

OpenAIAntBrain:
    # beta: 1.0e-2
    beta: 5.0e-3
    epsilon: 0.20
    gamma: 0.99
    lambd: 0.95
    learning_rate: 1.0e-3
    num_epoch: 3
    time_horizon: 128
    summary_freq: 1000
    use_recurrent: false
    normalize: true
    batch_size: 2048
    buffer_size: 10240
    num_layers: 3
    hidden_units: 53
    max_steps: 3e5
    # use_curiosity: true
    # curiosity_strength: 0.01
    # curiosity_enc_size: 256    

# DeepMindHumanoidBrain:
#     learning_rate: 3.0e-3
#     num_epoch: 10 
#     time_horizon: 500 
#     summary_freq: 1000 
#     use_recurrent: false
#     normalize: true 
#     num_layers: 2
#     hidden_units: 64 
#     batch_size: 2048 
#     buffer_size: 10240 
#     # max_steps: 62500
#     # max_steps: 625000
#     max_steps: 2e6

# DeepMindHopperBrain:
#     learning_rate: 3.0e-3
#     num_epoch: 10 
#     time_horizon: 500 
#     summary_freq: 1000 
#     use_recurrent: false
#     normalize: true 
#     num_layers: 2
#     hidden_units: 64 
#     batch_size: 2048 
#     buffer_size: 10240 
#     max_steps: 62500

# DeepMindWalkerBrain:
#     learning_rate: 3.0e-3
#     num_epoch: 10 
#     time_horizon: 500 
#     summary_freq: 1000 
#     use_recurrent: false
#     normalize: true 
#     num_layers: 2
#     hidden_units: 64 
#     batch_size: 2048 
#     buffer_size: 10240 
#     # max_steps: 62500
#     max_steps: 3e5

# OpenAIAntBrain:
#     learning_rate: 3.0e-3
#     num_epoch: 10 
#     time_horizon: 500 
#     summary_freq: 1000 
#     use_recurrent: false
#     normalize: true 
#     num_layers: 2
#     hidden_units: 64 
#     batch_size: 2048 
#     buffer_size: 10240 
#     max_steps: 62500  